### ISSUE TITLE
Uncaught Exceptions

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#1458]
I made a button that throws an exception:

```kotlin
Button(
  text = "Die",
  onClick = {
    throw RuntimeException("boom")
  }
)
```

It causes a severe failure: the host program exits immediately.

```
FATAL EXCEPTION: Treehouse
Process: com.squareup.cash.beta.debug, PID: 16870
app.cash.zipline.ZiplineException: RuntimeException: boom
	at captureStack (runtime/coreRuntime.kt:12)
	at RuntimeException_init_$Create$_0 (kotlin-kotlin-stdlib-js-ir.js)
	at PlaygroundHome$Show$composable$lambda$lambda$lambda (src/commonMain/kotlin/com/squareup/cash/treehouse/playground/PlaygroundHome.kt)
	at <anonymous> (arcade/compose-protocol/build/generated/redwood/app/cash/arcade/compose/arcade/ProtocolButton.kt:107)
	at <anonymous> (arcade/compose-protocol/build/generated/redwood/app/cash/arcade/compose/ArcadeProtocolBridge.kt:30)
	at <anonymous> (Users/colinwhite/redwood/redwood-treehouse-guest/src/commonMain/kotlin/app/cash/redwood/treehouse/treehouseCompose.kt)
	at <anonymous> (Users/colinwhite/redwood/redwood-treehouse/src/commonMain/kotlin/app/cash/redwood/treehouse/ZiplineTreehouseUi.kt)
	at <anonymous> (redwood-redwood-treehouse.js)
	at <anonymous> (zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/InboundService.kt:1391)
	at <anonymous> (zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/Endpoint.kt:99)
	at <anonymous> (zipline-root-zipline.js)
	at <anonymous> (zipline/zipline/src/jsMain/kotlin/app/cash/zipline/GlobalBridge.kt)
	at <anonymous> (zipline-root-zipline.js)
	at app.cash.redwood.treehouse.ZiplineTreehouseUi$Companion$Adapter$GeneratedOutboundService.sendEvent(ZiplineTreehouseUi.kt:29)
	at app.cash.redwood.treehouse.ViewContentCodeBinding$sendEvent$1.invokeSuspend(TreehouseAppContent.kt:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

Alternately I could launch a job before throwing the exception:

```kotlin
val scope = rememberCoroutineScope()

Button(
  text = "Die",
  onClick = {
    scope.launch {
      throw RuntimeException("boom")
    }
  }
)
```

With a job, guest code logs the exception and then cancels the guest side’s composition. There’s nothing in the UI that shows that the program has crashed, but the program stops responding to UI events.

```
app.cash.zipline.ZiplineException: RuntimeException: boom
	at captureStack (runtime/coreRuntime.kt:12)
	at RuntimeException_init_$Create$_0 (kotlin-kotlin-stdlib-js-ir.js)
	at <anonymous> (src/commonMain/kotlin/com/squareup/cash/treehouse/playground/PlaygroundHome.kt:58)
	at <anonymous> (src/commonMain/kotlin/com/squareup/cash/treehouse/playground/PlaygroundHome.kt:366)
	at l (treehouse-root-playground-treehouse-playground.js)
	at <anonymous> (src/kotlin/coroutines_13/IntrinsicsJs.kt:182)
	at <anonymous> (src/kotlin/coroutines_13/CoroutineImpl.kt:55)
	at <anonymous> (kotlin-kotlin-stdlib-js-ir.js)
	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:112)
	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/js/src/JSDispatcher.kt:155)
	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/js/src/JSDispatcher.kt)
	at apply (native)
	at <anonymous> (zipline/zipline/src/jsMain/kotlin/app/cash/zipline/GlobalBridge.kt:72)
	at <anonymous> (zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/GuestService.kt)
	at <anonymous> (zipline-root-zipline.js)
	at <anonymous> (zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/InboundService.kt:1391)
	at <anonymous> (zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/Endpoint.kt:99)
	at <anonymous> (zipline-root-zipline.js)
	at <anonymous> (zipline/zipline/src/jsMain/kotlin/app/cash/zipline/GlobalBridge.kt)
	at <anonymous> (zipline-root-zipline.js)
```

Both of these failure modes are accidents of implementation. I’d like to deliberately design what happens when a Treehouse application throws an unchecked exception in guest code.

### Some considerations...

We should design the API for uncaught exceptions to be delivered to the host application. This is probably something in `EventListener`, though it could also be a standalone interface like `UncaughtExceptionHandler`. 

[Failing fast](https://en.wikipedia.org/wiki/Fail-fast) is a good default.

If we fail too fast, we might crash while a code update is downloading. This would wedge the application on a bad version! Treehouse may be included on an application’s launch screen.

In interactive development, failing fast can be super annoying. A screen of interest might require several steps to navigate to, and crashing the entire process is punitive.

Web browsers successfully isolate crashes to the tabs that triggered them. We could do likewise, either for applications (ie. the `Zipline` instance) or for individual UIs (ie. a `ViewContentCodeBinding` instance). We can add an error state to crashed components, just as we’ve already done for loading states.

This policy could be configurable, and differ for development vs. production.

**Comment by swankjesse** [comment]
Plans!

Change `EventListener` to handle uncaught exceptions:

```
  /**
   * Invoked when [app] fails with an uncaught exception.
   * 
   * Implementations should report the exception to bug tracking
   * tools, and possibly crash the current process to allow the user
   * a chance to recover.
   * 
   * When a Treehouse app fails its current [Zipline] instance is
   * canceled so no further code will execute. A new [Zipline] will
   * start when new code available, or when the app is restarted 
   * with [TreehouseApp.restart].
   */
  public open fun onUncaughtException(
    app: TreehouseApp<*>,
    manifestUrl: String?,
    manifest: ZiplineManifest,
    exception: Exception,
  ) {}
```

Change `CodeListener` to support an error UI:

```
  /**
   * Invoked when the application powering [view] fails with an
   * uncaught exception. This function should only be used to
   * display error UI; use [EventListener.onUncaughtException] to
   * dispatch failures.
   *
   * Typical implementations call [TreehouseView.reset] and display
   * an error state placeholder. Development builds typically show
   * more diagnostic information than production builds.
   * 
   * When a Treehouse app fails its current [Zipline] instance is
   * canceled so no further code will execute. A new [Zipline] will
   * start when new code available, or when the app is restarted 
   * with [TreehouseApp.restart].
   * 
   * This condition is not permanent! If new code is loaded after an
   * error, [onCodeLoaded] will be called.
   */
  public open fun onUncaughtException(
    app: TreehouseApp<*>,
    view: TreehouseView,
    manifestUrl: String?,
    manifest: ZiplineManifest,
    exception: Exception,
  ) {}
```

Once we’ve got this, we need to change Redwood to make these APIs work as they’re documented.

**Comment by dnagler** [comment]
I like that this delineates levels of severity (i.e. giving a choice between displaying an error state and crashing), but I think I would prefer the two methods to have different names, to make it more obvious when to use one or the other. As it stands, they feel like overloads of the same method.

**Comment by jingwei99** [comment]
There are a few different topics came to my mind when I see this problem (& read through the considerations and plans):

1) 
> If we fail too fast, we might crash while a code update is downloading
This is super valid. I've had past experiences dealing with feature flags not delivered early enough so there's no way to get the app out of a crash cycle other than with a hot fix (dot release). 

I think there are ways to differentiate: 
a) code is still getting downloaded, print a log of the exception  
b) code downloading completed, crash/fail early 

2) 
> This policy could be configurable, and differ for development vs. production.
Crashing in debug and then log in prod would proactively save lots SEVs down the line: 
a) When engineers working on the implementation get a crash, it's a strong signal, and engineers likely will still contributing to code that's owned by different teams (or without active owners) 
b) It helps the QA process, when QA works with the build, they usually don't see logs, but they bring more thorough coverage to the app. 

3) 
> In interactive development, failing fast can be super annoying. A screen of interest might require several steps to navigate to, and crashing the entire process is punitive.

Agreed. There can be a debug menu toggle for the developer to choose between crash or log, iff the idea is to make it configurable between dev build vs prod.

Related to 2), the build QA work with should be config'ed to crash.

**Comment by swankjesse** [comment]
Next steps after the above PRs land:

 * [x] More contextual information in EventListener. We should include Zipline + ZiplineManifest instances whenever possible
 * [x] Add a mechanism on CodeHost to trigger a restart without a code change
 * [x] Add an exception screen to EmojiSearch on iOS

**Comment by swankjesse** [comment]
Last thing . . . maybe pass a `TreehouseApp` or similar to `CodeListener` so it has an easy mechanism to trigger a restart? Alternately it can get that via DI.

**Comment by swankjesse** [comment]
No further action to take on this. 🎉
