### ISSUE TITLE
Android View-based Emoji Search sample crashes because "no more placeholders!"

### ISSUE THREAD

**Issue by dellisd** [cashapp/redwood#1696]
Stacktrace:

```
FATAL EXCEPTION: main
Process: com.example.redwood.emojisearch.android.views, PID: 26278
java.lang.IllegalStateException: no more placeholders!
	at app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor.takePlaceholder(LazyListUpdateProcessor.kt:317)
	at app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor.requireBindingAtIndex$createBinding(LazyListUpdateProcessor.kt:305)
	at app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor.requireBindingAtIndex(LazyListUpdateProcessor.kt:311)
	at app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor.bind(LazyListUpdateProcessor.kt:291)
	at app.cash.redwood.lazylayout.view.ViewLazyList$LazyContentItemListAdapter.onBindViewHolder(ViewLazyList.kt:255)
	at app.cash.redwood.lazylayout.view.ViewLazyList$LazyContentItemListAdapter.onBindViewHolder(ViewLazyList.kt:225)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5789)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by JakeWharton** [comment]
~~#537 is unblocked. We really need to get even the most basic smoke test of emoji in here ASAP. Maybe I'll attempt it tonight...~~

Remove the `@Ignore` on the UI test once fixed
