### ISSUE TITLE
JVM targets are compiling against JDK 21 API with Java 8 bytecode

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#1863]
Normally this wouldn't be a problem, but JDK 21 added a `removeFirst()` function to `List`. Kotlin also has this function as an extension, but the member takes precedence.

```
RealErrorReporter W java.lang.NoSuchMethodError: No interface method removeFirst()Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
                         	at app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor.onEndChanges(SourceFile:165)
                         	at app.cash.redwood.lazylayout.view.ViewLazyList.onEndChanges(SourceFile:210)
                         	at app.cash.redwood.protocol.widget.ProtocolBridge.sendChanges(SourceFile:125)
                         	at app.cash.redwood.treehouse.ViewContentCodeBinding.receiveChangesOnUiDispatcher(SourceFile:419)
                         	at app.cash.redwood.treehouse.ViewContentCodeBinding.access$receiveChangesOnUiDispatcher(SourceFile:294)
                         	at app.cash.redwood.treehouse.ViewContentCodeBinding$sendChanges$1.invokeSuspend(SourceFile:383)
                         	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
                         	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
                         	at android.os.Handler.handleCallback(Handler.java:938)
                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                         	at android.os.Looper.loop(Looper.java:250)
                         	at android.app.ActivityThread.main(ActivityThread.java:7868)
                         	at java.lang.reflect.Method.invoke(Native Method)
                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

We need to be using `javac`'s `--release` flag for JVM targets which will use the JDK 8 API set in addition to setting the source and target bytecode versions.

**Comment by JakeWharton** [comment]
```
javap --class-path ~/Downloads/redwood-lazylayout-widget-jvm-0.9.0.jar -c -p app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor | \grep -C 3 'java/util/List.removeFirst'
304-     404: aload_3
305-     405: checkcast     #101                // class app/cash/redwood/lazylayout/widget/LazyListUpdateProcessor$Edit$Insert
306-     408: invokevirtual #107                // Method app/cash/redwood/lazylayout/widget/LazyListUpdateProcessor$Edit$Insert.getWidgets:()Ljava/util/List;
307:     411: invokeinterface #151,  1          // InterfaceMethod java/util/List.removeFirst:()Ljava/lang/Object;
308-     416: checkcast     #121                // class app/cash/redwood/widget/Widget
309-     419: astore        6
310-     421: aload_0
```
