### ISSUE TITLE
IndexOutOfBoundsException in LazyListUpdateProcessor

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#2140]
We’re seeing this crash:

```
IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:763)
        at java.util.ArrayList.addAll(ArrayList.java:707)
        at app.cash.redwood.lazylayout.widget.SparseList.addRange(SparseList:126)
        at app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor.maybeShiftLoadedWindow(LazyListUpdateProcessor:307)
        at app.cash.redwood.lazylayout.widget.LazyListUpdateProcessor.onEndChanges(LazyListUpdateProcessor:174)
        at app.cash.redwood.lazylayout.view.ViewLazyList.onEndChanges(ViewLazyList:209)
        at app.cash.redwood.protocol.host.ProtocolBridge.sendChanges(ProtocolBridge:151)
        at app.cash.redwood.treehouse.ViewContentCodeBinding.receiveChangesOnUiDispatcher(ViewContentCodeBinding:411)
        at app.cash.redwood.treehouse.ViewContentCodeBinding.access$receiveChangesOnUiDispatcher(ViewContentCodeBinding:295)
        at app.cash.redwood.treehouse.ViewContentCodeBinding$sendChanges$1.invokeSuspend(ViewContentCodeBinding:374)
```

I was able to reproduce the exception with this test, that adds a range beyond the end of the list.

```
  @Test
  fun addRangeOutOfBounds() {
    val source = SparseList<String?>()
    source.add("A")
    source.add("B")
    source.add("C")

    val target = SparseList<String?>()
    target.addNulls(0, 5)

    target.addRange(6, source, sourceIndex = 1, count = 2)
  }
```

I expect we have a fencepost error in `LazyListState.kt`.

**Comment by dnagler** [comment]
This is fixed with PR #2142
