### ISSUE TITLE
Crash when hot reloading

### ISSUE THREAD

**Issue by colinrtwhite** [cashapp/redwood#892]
I'm running into the following crash when performing a hot reload:

```
04-02 21:22:14.639 12459 12459 E AndroidRuntime: java.lang.IllegalStateException: unexpected receiveZiplineSession with no view bound and no preload
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at app.cash.redwood.treehouse.TreehouseAppContent.receiveZiplineSession$redwood_treehouse_host_release(TreehouseAppContent.kt:171)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at app.cash.redwood.treehouse.TreehouseApp$onCodeChanged$1.invokeSuspend(TreehouseApp.kt:182)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-02 21:22:14.639 12459 12459 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

cc @veyndan seems potentially related to https://github.com/cashapp/redwood/pull/870?

Related: https://github.com/cashapp/redwood/pull/891/files

**Comment by JakeWharton** [comment]
Also related: #537

**Comment by colinrtwhite** [comment]
@swankjesse I'm still able to reproduce this crash in the `emoji-search` sample.

**Comment by swankjesse** [comment]
@colinrtwhite I think it was an issue with the old LazyList. Seems to be taking updates without crashing now!
